# Generated by Django 5.1.3 on 2024-11-13 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, verbose_name='单词内容')),
                ('explanatory_in_chinese', models.CharField(max_length=100, verbose_name='单词解释用中文')),
                ('explanatory_in_english', models.CharField(max_length=100, verbose_name='单词翻译用英文')),
                ('remark_of_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='单词备注')),
                ('scene_example_sentence', models.TextField(max_length=500, verbose_name='场景例句')),
                ('translation_of_sentence', models.TextField(max_length=500, verbose_name='例句翻译')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联的用户')),
            ],
            options={
                'verbose_name': '单词卡',
                'verbose_name_plural': '单词卡',
            },
        ),
        migrations.CreateModel(
            name='UsefulPhraseUsingThisVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=50, verbose_name='内容')),
                ('translation', models.TextField(max_length=50, verbose_name='翻译')),
                ('scene_example_sentence', models.TextField(max_length=500, verbose_name='例句')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联的用户')),
                ('word_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_usages', to='card_module.wordcard', verbose_name='关联的单词')),
            ],
            options={
                'verbose_name': '使用该词汇的相关短语',
                'verbose_name_plural': '使用该词汇的相关短语',
            },
        ),
        migrations.CreateModel(
            name='RootExplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(max_length=100, verbose_name='词根')),
                ('explain', models.TextField(max_length=500, verbose_name='词根解释')),
                ('cognates_description', models.TextField(max_length=500, verbose_name='补充描述')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联的用户')),
                ('word_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_explains', to='card_module.wordcard', verbose_name='关联的单词')),
            ],
            options={
                'verbose_name': '词根解释',
                'verbose_name_plural': '词根解释',
            },
        ),
    ]
