# Generated by Django 5.1.3 on 2024-11-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcard',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='wordcard',
            name='explanatory_in_english',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='单词翻译用英文'),
        ),
        migrations.AlterField(
            model_name='wordcard',
            name='scene_example_sentence',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='场景例句'),
        ),
        migrations.AlterField(
            model_name='wordcard',
            name='translation_of_sentence',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='例句翻译'),
        ),
        migrations.AlterField(
            model_name='wordcard',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
