#!/bin/sh
# 收集静态文件
python manage.py collectstatic --noinput
# 生成迁移文件
python manage.py makemigrations
# 执行迁移
python manage.py migrate
# 启动uwsgi
cd /app || exit
# 启动uwsgi和nginx
uwsgi --enable-threads --ini uwsgi/uwsgi.ini
# & python funboost_consume.py
