# Generated by Django 5.1.3 on 2024-11-13 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_phase', models.IntegerField(choices=[(-1, '无需复习'), (-2, '记忆完成'), (0, '初始阶段，刚加入'), (1, '阶段1 完成学习，距离下次复习还有1天'), (2, '阶段2 完成第一次复习，距离下次复习还有3天'), (3, '阶段3 完成第二次复习，距离下次复习还有7天'), (4, '阶段4 完成第三次复习，距离下次复习还有14天'), (5, '阶段5 完成第四次复习，距离下次复习还有30天')], verbose_name='记忆阶段')),
                ('next_review_date', models.DateTimeField(blank=True, null=True, verbose_name='下次复习时间')),
                ('last_reviewed_date', models.DateTimeField(blank=True, null=True, verbose_name='上次复习时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='关联的用户')),
                ('word_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_schedule', to='card_module.wordcard', verbose_name='单词卡')),
            ],
            options={
                'verbose_name': '记忆计划',
                'verbose_name_plural': '记忆计划',
            },
        ),
    ]
